[project]
name = "litellm-eval"
version = "0.1.0"
description = "LiteLLM evaluation environment"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
docker-compose = "*"

[tasks]
# Start LiteLLM services
up = "docker-compose up -d"

# Stop LiteLLM services
down = "docker-compose down"

# View logs
logs = "docker-compose logs -f"

# Check service status
status = "docker-compose ps"

# Restart services
restart = "docker-compose restart"

# Clean up volumes (WARNING: This will delete all data)
clean = "docker-compose down -v"
